# version: '2'

services:
  nginx:
    image: nginx
    hostname: nginx
    domainname: nginx
    volumes:
      - /home/luki/Study/PARVPO/PARVPO/lab2.b/nginx.conf:/etc/nginx/nginx.conf
      - /home/luki/Study/PARVPO/PARVPO/lab2.b/nginx-default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - consumer_1
      - consumer_2
      - consumer_3
        #- producer1
        #- producer2
    networks:
      lab2network:
        aliases:
          - nginx-name
          - alias1
          - alias2

  producer1:
    build:
      context: ./producer1
      no_cache: true
    env_file:
      - ./MSize.env
    depends_on:
      - nginx
        #- consumer_1
        #- consumer_2
    networks:
      - lab2network

  producer2:
    build:
      context: ./producer2
      no_cache: true
    env_file:
      - ./MSize.env
    depends_on:
      - nginx
        #- consumer_1
        #- consumer_2
    networks:
      - lab2network

  consumer_1:
    build:
      context: ./consumer
      no_cache: true
    depends_on:
      - adder
    networks:
      - lab2network
    deploy:
      resources:
        limits:
          cpus: "3"

  consumer_2:
    build:
      context: ./consumer
      no_cache: true
    depends_on:
      - adder
    networks:
      - lab2network
    deploy:
      resources:
        limits:
          cpus: "3"

  consumer_3:
    build:
      context: ./consumer
      no_cache: true
    depends_on:
      - adder
    networks:
      - lab2network
    deploy:
      resources:
        limits:
          cpus: "3"

  # adder:
  #   build:
  #     context: ./adder
  #     no_cache: true
  #   networks:
  #     - lab2network

  adder:
    build:
      context: ./adder-py
      no_cache: true
    networks:
      - lab2network

networks:
  lab2network:
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.28.0.0/16
#          ip_range: 172.28.5.0/24
#          gateway: 172.28.5.254
#          aux_addresses:
#            host1: 172.28.1.5
#            host2: 172.28.1.6
#            host3: 172.28.1.7
